# **TUGAS 2**
Diskritisasi


*   Carilah data yang bertipe numerik ( data klassifikasi)
*   Lakukan proses diskritisasi dengan equal width dan equal frequency
*   Lakukan proses diskritisasi dengan basis entropy




##**1.   Pengertian**
  
  

*   Diskritisasi yaitu proses mengubah data numerik menjadi data kategorikal

##**2.   Metode**

  *   Diskritisasi dengan Equal Width dan Equal Frequency 
      *   Equal width : dikritisasi yang membagi data numerik menjadi beberapa kelompok dengan lebar kelompok yang kurang lebih sama besar. 
      *   Equal frequency : dikritisasi yang membagi data numerik menjadi beberapa kelompok dengan jumlah anggota per kelompok yang kurang lebih sama besar.
  *   Diskritisasi dengan basis Entropy

       Entropy digunakan untuk menentukan yang manakah node yang akan
menjadi pemecah data latih berikutnya

          Rumus Entropi
      
      ![image.png](https://cdn.mathpix.com/snip/images/T3MAnkOgvu54ASi68sQ5fR96rPCLPxjYofOqC9L4IpM.original.fullsize.png)

          Rumus Gain

  ![image.png](https://cdn.mathpix.com/snip/images/T6pg-dpJKT4PsSKzNdI_sQWFKj1kZao_9Oaf5-Zf88g.original.fullsize.png)

          Rumus Info 

         ![image.png](https://cdn.mathpix.com/snip/images/iFDk6peaL_uAebWnVWZebfy9CvJ0VNADb8ukE2Nmyds.original.fullsize.png)


##**3. Implementasi Code**

In [ ]:
import warnings
warnings.filterwarnings('ignore', category=UserWarning, append=True)

In [ ]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import KBinsDiscretizer
url = 'https://raw.githubusercontent.com/normalitariyn/mydataset/main/IRIS.csv'
c=pd.read_csv(url)

In [ ]:
c

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# CONSTAN SERIES

# mengambil hanya kolom species 
iris_class = pd.DataFrame(c["species"])

# mengambil data iris tanpa class/label
iris_data = c.drop(columns = "species")

**Library Scikit Learn dengan modul KBinsDiscritizer**

Digunakan untuk melakukkan binning data dengan pendekatan equal width dan equal frequency

    #syntax
    KBinsDiscretizer(n_bins = amount_of_binning, encode, strategy)

Keterangan
*  n_bins adalah jumlah banyaknya kategori yang digunakan 
*  encode adalah jenis tipe data dari hasil output, gunakan value = “encode” sehingga data keluaran bertipe integer
*  strategy digunakan untuk menentukan jangka interval antara data
    - strategy = “uniform” digunakan untuk pendekatan equal width
    - strategy = “quantile” digunakan untuk pendekatan equal frequency
*  strategy = “quantile” digunakan untuk pendekatan equal frequency
*  Dikelompokkan menjadi 3 kategori yaitu :
    - Kategori sedikit lebar
    - Kategori lebar
    - Kategori sangat lebar

    # pseudocode #
    if value == 0.0 then sedikit lebar
    if value == 1.0 then lebar
    else sangat lebar

In [ ]:
# set category and n bin
labels = ["Sedikit_Lebar", "Lebar", "Sangat_Lebar"]
amount_of_binning = len(labels)



###   **Equal Width**



*   Untuk menghitung equal width, dibutuhkan library pandas dengan menggunakan strategy = “uniform”. Buat 3 label untuk mengkategorikan batas tiap ukuran petal dan sepal dengan menggunakan small, medium, large.

In [ ]:
# equal-width intervals binning
est_ew_binning = KBinsDiscretizer(n_bins=amount_of_binning, encode='ordinal', strategy='uniform')

In [ ]:
# fit estimator
est_ew_binning.fit(iris_data)

# fit to data
iris_ew_binning = est_ew_binning.transform(iris_data)
value_of_ew_binned_df = pd.DataFrame(iris_ew_binning, columns=["sepal.length","sepal.width", "petal.length","petal.width"])
value_of_ew_binned_df

     sepal.length  sepal.width  petal.length  petal.width
0             0.0          1.0           0.0          0.0
1             0.0          1.0           0.0          0.0
2             0.0          1.0           0.0          0.0
3             0.0          1.0           0.0          0.0
4             0.0          2.0           0.0          0.0
..            ...          ...           ...          ...
145           2.0          1.0           2.0          2.0
146           1.0          0.0           2.0          2.0
147           1.0          1.0           2.0          2.0
148           1.0          1.0           2.0          2.0
149           1.0          1.0           2.0          2.0

[150 rows x 4 columns]

In [ ]:
# categorize every iris data
ew_binned_df = pd.DataFrame(iris_ew_binning, columns=["sepal.length", "sepal.width", "petal.length", "petal.width"])
ew_binned_df["sepal.length"] = np.where(ew_binned_df["sepal.length"] == 0.0, "Sedikit_Lebar", np.where(ew_binned_df["sepal.length"] == 1.0, "Lebar", "Sangat_Lebar"))
ew_binned_df["sepal.width"] = np.where(ew_binned_df["sepal.width"] == 0.0, "Sedikit_Lebar", np.where(ew_binned_df["sepal.width"] == 1.0, "Lebar", "Sangat_Lebar"))
ew_binned_df["petal.length"] = np.where(ew_binned_df["petal.length"] == 0.0, "Sedikit_Lebar", np.where(ew_binned_df["petal.length"] == 1.0, "Lebar", "Sangat_Lebar"))
ew_binned_df["petal.width"] = np.where(ew_binned_df["petal.width"] == 0.0, "Sedikit_Lebar", np.where(ew_binned_df["petal.width"] == 1.0, "Lebar", "Sangat_Lebar"))

In [ ]:
# create data frame from binned iris data and iris variety
class_of_ew_binned_df = pd.concat((ew_binned_df, iris_class), axis = 1)
class_of_ew_binned_df

,sepal.length,sepal.width,petal.length,petal.width,species
0,Sedikit_Lebar,Lebar,Sedikit_Lebar,Sedikit_Lebar,Iris-setosa
1,Sedikit_Lebar,Lebar,Sedikit_Lebar,Sedikit_Lebar,Iris-setosa
2,Sedikit_Lebar,Lebar,Sedikit_Lebar,Sedikit_Lebar,Iris-setosa
3,Sedikit_Lebar,Lebar,Sedikit_Lebar,Sedikit_Lebar,Iris-setosa
4,Sedikit_Lebar,Sangat_Lebar,Sedikit_Lebar,Sedikit_Lebar,Iris-setosa
...,...,...,...,...,...
145,Sangat_Lebar,Lebar,Sangat_Lebar,Sangat_Lebar,Iris-virginica
146,Lebar,Sedikit_Lebar,Sangat_Lebar,Sangat_Lebar,Iris-virginica
147,Lebar,Lebar,Sangat_Lebar,Sangat_Lebar,Iris-virginica
148,Lebar,Lebar,Sangat_Lebar,Sangat_Lebar,Iris-virginica
149,Lebar,Lebar,Sangat_Lebar,Sangat_Lebar,Iris-virginica

In [ ]:
# categorize every iris data
ef_binned_df = pd.DataFrame(est_ef_binning, columns=["sepal.length", "sepal.width", "petal.length", "petal.width"])
ef_binned_df["sepal.length"] = np.where(ef_binned_df["sepal.length"] == 0.0, "Sedikit_Lebar", np.where(ef_binned_df["sepal.length"] == 1.0, "Lebar", "Sangat_Lebar"))
ef_binned_df["sepal.width"] = np.where(ef_binned_df["sepal.width"] == 0.0, "Sedikit_Lebar", np.where(ef_binned_df["sepal.width"] == 1.0, "Lebar", "Sangat_Lebar"))
ef_binned_df["petal.length"] = np.where(ef_binned_df["petal.length"] == 0.0, "Sedikit_Lebar", np.where(ef_binned_df["petal.length"] == 1.0, "Lebar", "Sangat_Lebar"))
ef_binned_df["petal.width"] = np.where(ef_binned_df["petal.width"] == 0.0, "Sedikit_Lebar", np.where(ef_binned_df["petal.width"] == 1.0, "Lebar", "Sangat_Lebar"))

In [ ]:
# create data frame from binned iris data and iris variety
class_of_ef_binned_df = pd.concat((ef_binned_df, iris_class), axis = 1)
class_of_ef_binned_df

,sepal.length,sepal.width,petal.length,petal.width,species
0,Sedikit_Lebar,Sangat_Lebar,Sedikit_Lebar,Sedikit_Lebar,Iris-setosa
1,Sedikit_Lebar,Lebar,Sedikit_Lebar,Sedikit_Lebar,Iris-setosa
2,Sedikit_Lebar,Sangat_Lebar,Sedikit_Lebar,Sedikit_Lebar,Iris-setosa
3,Sedikit_Lebar,Lebar,Sedikit_Lebar,Sedikit_Lebar,Iris-setosa
4,Sedikit_Lebar,Sangat_Lebar,Sedikit_Lebar,Sedikit_Lebar,Iris-setosa
...,...,...,...,...,...
145,Sangat_Lebar,Lebar,Sangat_Lebar,Sangat_Lebar,Iris-virginica
146,Sangat_Lebar,Sedikit_Lebar,Sangat_Lebar,Sangat_Lebar,Iris-virginica
147,Sangat_Lebar,Lebar,Sangat_Lebar,Sangat_Lebar,Iris-virginica
148,Lebar,Sangat_Lebar,Sangat_Lebar,Sangat_Lebar,Iris-virginica
149,Lebar,Lebar,Sangat_Lebar,Sangat_Lebar,Iris-virginica

*sepal length*

In [ ]:
class_of_ew_binned_df["sepal.length"].value_counts()

Lebar            70
Sedikit_Lebar    52
Sangat_Lebar     28
Name: sepal.length, dtype: int64

*sepal width*

In [ ]:
class_of_ew_binned_df["sepal.width"].value_counts()

Lebar            99
Sedikit_Lebar    33
Sangat_Lebar     18
Name: sepal.width, dtype: int64

*Petal Length*

In [ ]:
class_of_ew_binned_df["petal.length"].value_counts()

Lebar            54
Sedikit_Lebar    50
Sangat_Lebar     46
Name: petal.length, dtype: int64

*Petal Width*

In [ ]:
class_of_ew_binned_df["petal.width"].value_counts()

Lebar            52
Sedikit_Lebar    50
Sangat_Lebar     48
Name: petal.width, dtype: int64



###   **Equal Frequency**

  Untuk menghitung equal frequency, dibutuhkan library pandas dengan menggunakan method strategy = “quantile”.

In [ ]:
# equal-frequency intervals binning
est_ef_binning = KBinsDiscretizer(n_bins=amount_of_binning, encode='ordinal', strategy='quantile')

In [ ]:
# create dataframe of sepal-width

# fit estimator
est_ef_binning.fit(iris_data)

# fit to data
est_ef_binning = est_ef_binning.transform(iris_data)
value_of_ef_binned_df = pd.DataFrame(est_ef_binning, columns=["sepal.length","sepal.width", "petal.length","petal.width"])
value_of_ef_binned_df

     sepal.length  sepal.width  petal.length  petal.width
0             0.0          2.0           0.0          0.0
1             0.0          1.0           0.0          0.0
2             0.0          2.0           0.0          0.0
3             0.0          1.0           0.0          0.0
4             0.0          2.0           0.0          0.0
..            ...          ...           ...          ...
145           2.0          1.0           2.0          2.0
146           2.0          0.0           2.0          2.0
147           2.0          1.0           2.0          2.0
148           1.0          2.0           2.0          2.0
149           1.0          1.0           2.0          2.0

[150 rows x 4 columns]

*Sepal Length*

In [ ]:
class_of_ef_binned_df["sepal.length"].value_counts()

Lebar            53
Sangat_Lebar     51
Sedikit_Lebar    46
Name: sepal.length, dtype: int64

*Sepal Width*

In [ ]:
class_of_ef_binned_df["sepal.width"].value_counts()

Sangat_Lebar     55
Lebar            48
Sedikit_Lebar    47
Name: sepal.width, dtype: int64

*Petal Length*

In [ ]:
class_of_ef_binned_df["petal.length"].value_counts()

Sangat_Lebar     51
Sedikit_Lebar    50
Lebar            49
Name: petal.length, dtype: int64

*Petal Width*

In [ ]:
class_of_ef_binned_df["petal.width"].value_counts()

Sangat_Lebar     52
Sedikit_Lebar    50
Lebar            48
Name: petal.width, dtype: int64

*jumlah per class*

In [ ]:
class_of_ef_binned_df["species"].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: species, dtype: int64

###**Basis Entropy**



*   Metode untuk mengelompokkan data numeric menjadi categorical
*   Pengelompokkan dengan mencari jumlah pembagi yang terbaik
*   Hasil pengelompokkan terbaik adalah dengan entropy gain yang paling besar

Data yang digunakan
    # value of binned dataframe (Equeal Frequency Interval)
    df["sepal.length"

    # class of binned dataframe (Equeal Frequency Interval)
    class_of_ef_binned_df

Label yang digunakan 

    labels = ["sedikit_lebar", "lebar", "sangat_lebar"]

In [ ]:
# module to calculate log
from math import log2

In [ ]:
column_target_value = pd.DataFrame(c["petal_width"])
column_target_value

     petal_width
0            0.2
1            0.2
2            0.2
3            0.2
4            0.2
..           ...
145          2.3
146          1.9
147          2.0
148          2.3
149          1.8

[150 rows x 1 columns]

In [ ]:
column_target_class = pd.DataFrame(class_of_ef_binned_df["petal.width"])
column_target_class

       petal.width
0    Sedikit_Lebar
1    Sedikit_Lebar
2    Sedikit_Lebar
3    Sedikit_Lebar
4    Sedikit_Lebar
..             ...
145   Sangat_Lebar
146   Sangat_Lebar
147   Sangat_Lebar
148   Sangat_Lebar
149   Sangat_Lebar

[150 rows x 1 columns]

In [ ]:
# create data target for entropy gain
target_data = pd.DataFrame(pd.concat((c["petal_width"], class_of_ef_binned_df["petal.width"]), axis = 1))

# change columns name of target data
target_data.columns = ["value", "category"]
target_data

     value       category
0      0.2  Sedikit_Lebar
1      0.2  Sedikit_Lebar
2      0.2  Sedikit_Lebar
3      0.2  Sedikit_Lebar
4      0.2  Sedikit_Lebar
..     ...            ...
145    2.3   Sangat_Lebar
146    1.9   Sangat_Lebar
147    2.0   Sangat_Lebar
148    2.3   Sangat_Lebar
149    1.8   Sangat_Lebar

[150 rows x 2 columns]

Functions

Fungsi menghitung banyaknya data setiap kategori

In [ ]:
# count every value based the given category
def countEveryCategory(data_column, labels, column, category):
    group = data_column.groupby(category).count()
    amount_of_every_category = []
    for label in labels:
        if label not in group.index:
            amount_of_every_category.append(0)
        else:
            amount_of_every_category.append(group.loc[label, column])
    return amount_of_every_category

In [ ]:
countEveryCategory(target_data, labels, target_data.columns[0], target_data.columns[1])

[50, 48, 52]

Fungsi menghitung banyaknya data setiap kategori berdasarkan nilai pembagi atau split value yang diberikan

In [ ]:
# split the given data based on category and split value 
def split(split_value, data_column, labels, col, category):
    less_group = data_column[data_column[col] < split_value]
    greater_group = data_column[data_column[col] >= split_value]
    
    length_less_group = countEveryCategory(less_group, labels, col, category)
    length_greater_group = countEveryCategory(greater_group, labels, col, category)
    
    return (length_less_group, length_greater_group)

Fungsi menghitung perbedaan gain antara entropi inisial dengan entropi nilai pembagi yang diberikan

In [ ]:
# count information gain from inisial entropy and new entropy
def count_gain(inisial_entropy, new_entropy):
  return inisial_entropy - new_entropy

Fungsi menghitung entropy

In [ ]:
# count entropy
def count_entropy(data_target):
    all_prob = []
    for prob in data_target:
        if (prob/sum(data_target) != 0):
            all_prob.append(prob/sum(data_target) * log2(prob/sum(data_target)))
        else:
            all_prob.append(0)
    return -(sum(all_prob))

Fungsi menghitung Info entropy berdasarkan nilai pembagi atau split value yang diberikan

In [ ]:
# count entropy for given a split value
def info(d, data_target):
    temp = []
    for value in d:
        temp.append((sum(value) / data_target.shape[0]) * count_entropy(value))
    return sum(temp)

Implementasi

* Hitung target entropy

Hitung target entropy dengan split value

Hitung entropy gain

Entropy inisial atau awal

In [ ]:
# entropy data target
initial_data_target_entropy = count_entropy(countEveryCategory(target_data, labels, target_data.columns[0], target_data.columns[1]))

Entropy uji coba 1

* Nilai split yaitu 0.7
* Data kurang dari  <0.7 
* Data kurang dari  >=0.7

In [ ]:
# count Entropy for the target given a split value, split value = 0.7
entropy_data_target_1 = info(split(0.7, target_data, labels, target_data.columns[0], target_data.columns[1]), target_data)

Entropy uji coba 2
* Nilai split yaitu  1.4 
* Data kurang dari  <1.4 
* Data kurang dari  >=1.4

In [ ]:
# count Entropy for the target given a split value, split value = 1.4
entropy_data_target_2 = info(split(1.4, target_data, labels, target_data.columns[0], target_data.columns[1]), target_data)

Entropy uji coba 3
* Nilai split yaitu  2.1 
* Data kurang dari  <2.1 
* Data kurang dari  >=2.1

In [ ]:
# count Entropy for the target given a split value, split value = 2.1
entropy_data_target_3 = info(split(2.1, target_data, labels, target_data.columns[0], target_data.columns[1]), target_data)

$Gain(E_{new}) = (E_{initial}) \ - (E_{target\ data\ 1})$

In [ ]:
# information gain (entropy data target and entropy_data_target_1)
count_gain(initial_data_target_entropy, entropy_data_target_1)

0.9182958340544896

$Gain(E_{new}) = (E_{initial}) \ - (E_{target\ data\ 2})$

In [ ]:
# information gain (entropy data target and entropy_data_target_2)
count_gain(initial_data_target_entropy, entropy_data_target_2)

0.6852875338668329

$Gain(E_{new}) = (E_{initial}) \ - (E_{target\ data\ 3})$

In [ ]:
# information gain (entropy data target and entropy_data_target_3)
count_gain(initial_data_target_entropy, entropy_data_target_3)

0.27478954579786574