# **Statistik Deskriptif**

## **1. Membaca Data Dari URL**

*mengimport url*

In [ ]:
import pandas as pd
#c = pd.read_csv('https://raw.githubusercontent.com/normalitariyn/mydataset/main/volcano-events0-21.csv')
url ='https://raw.githubusercontent.com/normalitariyn/mydataset/main/Monkey_Pox_Cases_Worldwide.csv' 
c=pd.read_csv(url)

*menampilkan dataset*

In [ ]:
c

,Country,Confirmed_Cases,Suspected_Cases,Hospitalized,Travel_History_Yes,Travel_History_No
0,England,3257.0,0.0,5.0,2.0,7.0
1,Portugal,846.0,0.0,0.0,0.0,34.0
2,Spain,6543.0,0.0,13.0,2.0,0.0
3,United States,18879.0,0.0,4.0,41.0,11.0
4,Canada,1228.0,9.0,1.0,5.0,0.0
...,...,...,...,...,...,...
116,Central African Republic,8.0,9.0,0.0,0.0,0.0
117,Republic of Congo,3.0,5.0,0.0,0.0,0.0
118,Cameroon,7.0,27.0,0.0,0.0,0.0
119,Liberia,2.0,0.0,0.0,0.0,0.0
120,Sierra Leone,0.0,2.0,0.0,0.0,0.0

## **2. Membuat Statistik Diskriptif dari Data**





*   menggunakan fungsi describe

In [ ]:
c.describe()

,Confirmed_Cases,Suspected_Cases,Hospitalized,Travel_History_Yes,Travel_History_No
count,121.000000,121.000000,121.000000,121.000000,121.000000
mean,427.892562,21.396694,1.181818,2.173554,0.727273
std,1927.455152,203.127156,2.860653,4.893325,3.612478
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,0.000000,0.000000,0.000000,0.000000
50%,6.000000,0.000000,0.000000,1.000000,0.000000
75%,70.000000,0.000000,1.000000,3.000000,0.000000
max,18879.000000,2217.000000,18.000000,41.000000,34.000000


*   **MEAN** 

    Mean merupakan salah satu ukuran gejala pusat. Mean dapat dikatakan sebagai wakil kumpulan data. Menentukan mean dapat dilakukan dengan cara menjumlahkan seluruh nilai data, kemudian membaginya dengan banyaknya data.

    **Rumus**
$$
\bar{x}=\frac{\sum x_i}{n}
$$

        Keterangan:
  $\bar{x}$ : nilai rata-rata

  $x_i$ : nilai data ke-i

  n       : banyaknya data

In [ ]:
# import library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

mean = {'Confirmed_Cases':np.mean(c['Confirmed_Cases']),
		'Suspected_Cases': np.mean(c['Suspected_Cases']),'Hospitalized':np.mean(c['Hospitalized']),
    'Travel_History_Yes':np.mean(c['Travel_History_Yes']),'Travel_History_No':np.mean(c['Travel_History_No'])}

df = pd.DataFrame(mean, index=['mean'])
df

,Confirmed_Cases,Suspected_Cases,Hospitalized,Travel_History_Yes,Travel_History_No
mean,427.892562,21.396694,1.181818,2.173554,0.727273


*   **MEDIAN**

      Median atau nilai tengah adalah salah satu ukuran pemusatan data. Cara berhitung median adalah pertama menyortir segugus data dari yang terkecil sampai terbesar (atau terbaliknya), lalu nilai pengamatan yang tepat di tengah-tengah bila jumlah datanya ganjil, atau rata-rata kedua pengamatan yang di tengah bila jumlah datanya genap, adalah nilai tengah.

      **Rumus**

      Untuk data ganjil:
$$
M e=X_{\frac{n+1}{2}}
$$

      Untuk data genap:
$$
M e=\frac{X_{\frac{n}{2}}+X_{\left(\frac{n}{2}+1\right)}}{2}
$$

In [ ]:
median = {'Confirmed_Cases':np.median(c['Confirmed_Cases']),
		'Suspected_Cases': np.median(c['Suspected_Cases']),'Hospitalized':np.median(c['Hospitalized']),
    'Travel_History_Yes':np.median(c['Travel_History_Yes']),'Travel_History_No':np.median(c['Travel_History_No'])}

df = pd.DataFrame(median, index=['median'])
df

,Confirmed_Cases,Suspected_Cases,Hospitalized,Travel_History_Yes,Travel_History_No
median,6.0,0.0,0.0,1.0,0.0



*   **MODUS**

      Modus merupakan suatu nilai yang mempunyai frekuensi paling banyak

In [ ]:
import statistics as st
from scipy import stats
modus = {'Confirmed_Cases':stats.mode(c['Confirmed_Cases']),
		'Suspected_Cases': stats.mode(c['Suspected_Cases']),'Hospitalized':stats.mode(c['Hospitalized']),
    'Travel_History_Yes':stats.mode(c['Travel_History_Yes']),'Insulin':stats.mode(c['Travel_History_Yes']),
    'Travel_History_No':stats.mode(c['Travel_History_No'])}
modus

{'Confirmed_Cases': ModeResult(mode=array([0.]), count=array([17])),
 'Suspected_Cases': ModeResult(mode=array([0.]), count=array([105])),
 'Hospitalized': ModeResult(mode=array([0.]), count=array([77])),
 'Travel_History_Yes': ModeResult(mode=array([0.]), count=array([52])),
 'Insulin': ModeResult(mode=array([0.]), count=array([52])),
 'Travel_History_No': ModeResult(mode=array([0.]), count=array([105]))}



*   **PERSENTIL**

    Persentil merupakan pembagian data terurut ke dalam 100 bagian sama banyak.

    **Rumus** :

$$
\mathrm{P}_{\mathrm{i}}=\text { data ke }-\frac{i(n+1)}{100}
$$

In [ ]:
percentile25 = {'Confirmed_Cases':np.percentile(c['Confirmed_Cases'],25),
		'Suspected_Cases':np.percentile(c['Suspected_Cases'],25),'Hospitalized':np.percentile(c['Hospitalized'],25),
    'Travel_History_Yes':np.percentile(c['Travel_History_Yes'],25),'Travel_History_No':np.percentile(c['Travel_History_No'],25)
    }

df = pd.DataFrame(percentile25, index=['25%'])
df

,Confirmed_Cases,Suspected_Cases,Hospitalized,Travel_History_Yes,Travel_History_No
25%,2.0,0.0,0.0,0.0,0.0

In [ ]:
percentile50 = {'Confirmed_Cases':np.percentile(c['Confirmed_Cases'],50),
		'Suspected_Cases':np.percentile(c['Suspected_Cases'],50),'Hospitalized':np.percentile(c['Hospitalized'],50),
    'Travel_History_Yes':np.percentile(c['Travel_History_Yes'],50),'Travel_History_No':np.percentile(c['Travel_History_No'],50)
    }

df = pd.DataFrame(percentile50, index=['50%'])
df

,Confirmed_Cases,Suspected_Cases,Hospitalized,Travel_History_Yes,Travel_History_No
50%,6.0,0.0,0.0,1.0,0.0

In [ ]:
percentile75 = {'Confirmed_Cases':np.percentile(c['Confirmed_Cases'],75),
		'Suspected_Cases':np.percentile(c['Suspected_Cases'],75),'Hospitalized':np.percentile(c['Hospitalized'],75),
    'Travel_History_Yes':np.percentile(c['Travel_History_Yes'],75),'Travel_History_No':np.percentile(c['Travel_History_No'],75)
    }

df = pd.DataFrame(percentile75, index=['75%'])
df

,Confirmed_Cases,Suspected_Cases,Hospitalized,Travel_History_Yes,Travel_History_No
75%,70.0,0.0,1.0,3.0,0.0


*   **STANDAR DEVIASI**

    Standar Deviasi atau Simpangan Baku adalah suatu nilai yang digunakan dalam menentukan persebaran data pada suatu sampel, sekaligus untuk melihat seberapa dekat data-data tersebut dengan nilai 'mean'

    **Rumus**


$S=\sqrt{\frac{\sum\left(x_i-\bar{x}\right)^2}{n}}$

$S=$ Standar deviasi

$x_i=$ nilai $\mathrm{x} \mathrm {ke-i}$

$\bar{x}=$ nilai rata-rata data

$n=$ jumlah data

In [ ]:
std = {'Confirmed_Cases':st.stdev(c['Suspected_Cases']),
		'Hospitalized':st.stdev(c['Hospitalized']),'Travel_History_Yes':st.stdev(c['Travel_History_Yes']),
    'Travel_History_No':st.stdev(c['Travel_History_No'])}

df = pd.DataFrame(std, index=['std'])
df

     Confirmed_Cases  Hospitalized  Travel_History_Yes  Travel_History_No
std       203.127156      2.860653            4.893325           3.612478

In [ ]:
# import library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# menentukan dataframe
Confirmed_Cases = c['Confirmed_Cases']
Suspected_Cases = c['Suspected_Cases']
Hospitalized = c["Hospitalized"]
Travel_History_Yes = c["Travel_History_Yes"]
Travel_History_No = c["Travel_History_No"]


# mencari mean, median dan modus

meanCC = Confirmed_Cases.mean()
medianCC = Confirmed_Cases.median()
modusCC = Confirmed_Cases.mode()

meanSC = Suspected_Cases.mean()
medianSC = Suspected_Cases.median()
modusSC = Suspected_Cases.mode()

meanH = Hospitalized.mean()
medianH = Hospitalized.median()
modusH = Hospitalized.mode()

meanTHY = Travel_History_Yes.mean()
medianTHY = Travel_History_Yes.median()
modusTHY = Travel_History_Yes.mode()

meanTHN = Travel_History_No.mean()
medianTHN = Travel_History_No.median()
modusTHN = Travel_History_No.mode()

# menampilkan ukuran nilai tengah
print("Confirmed Case -->",'Mean: ',meanCC,'Median: ',medianCC,'Modus: ',modusCC[0])
print("Susspected Case -->",'Mean: ',meanSC,'Median: ',medianSC,'Modus: ',modusSC[0])
print("Hospitalized -->",'Mean: ',meanH,'Median: ',medianH,'Modus: ',modusH[0])
print("Travel History Yes -->",'Mean: ',meanTHY,'Median: ',medianTHY,'Modus: ',modusTHY[0])
print("Travel History No -->",'Mean: ',meanTHY,'Median: ',medianTHY,'Modus: ',modusTHY[0])

#membuat tabel
from prettytable import PrettyTable
tabel = PrettyTable(["", "Confirmed Case", "Suspected Case", "Hospitalized", "Travel History Yes", "Travel History No"])
tabel.add_row(["Mean", meanCC, meanSC, meanH, meanTHY, meanTHN])
tabel.add_row(["Median", medianCC, medianSC, medianH, medianTHY, medianTHN])
tabel.add_row(["Modus", modusCC, modusSC, modusH, modusTHY, modusTHN])
print(tabel)

Confirmed Case --> Mean:  427.89256198347107 Median:  6.0 Modus:  0.0
Susspected Case --> Mean:  21.39669421487603 Median:  0.0 Modus:  0.0
Hospitalized --> Mean:  1.1818181818181819 Median:  0.0 Modus:  0.0
Travel History Yes --> Mean:  2.1735537190082646 Median:  1.0 Modus:  0.0
Travel History No --> Mean:  2.1735537190082646 Median:  1.0 Modus:  0.0
+--------+--------------------+-------------------+--------------------+--------------------+--------------------+
|        |   Confirmed Case   |   Suspected Case  |    Hospitalized    | Travel History Yes | Travel History No  |
+--------+--------------------+-------------------+--------------------+--------------------+--------------------+
|  Mean  | 427.89256198347107 | 21.39669421487603 | 1.1818181818181819 | 2.1735537190082646 | 0.7272727272727273 |
| Median |        6.0         |        0.0        |        0.0         |        1.0         |        0.0         |
| Modus  |      0    0.0      |      0    0.0     |      0    0.0      |      0    0.0      |      0    0.0      |
|        |   dtype: float64   |   dtype: float64  |   dtype: float64   |   dtype: float64   |   dtype: float64   |
+--------+--------------------+-------------------+--------------------+--------------------+--------------------+

## **3. Mendeskripsikan kemiringan/skewned dari data setiap variabel**

*tabel ditampilkan satu per satu*

In [ ]:
import seaborn as sns
sns.distplot(c['Confirmed_Cases'], hist=True, kde=True, bins=int (180/5), color= 'darkblue',hist_kws={'edgecolor': 'black'}, kde_kws={'linewidth':4})

In [ ]:
sns.distplot(c['Suspected_Cases'], hist=True, kde=True, bins=int (180/5), color= 'darkblue',hist_kws={'edgecolor': 'black'}, kde_kws={'linewidth':4})

In [ ]:
sns.distplot(c['Hospitalized'], hist=True, kde=True, bins=int (180/5), color= 'darkblue',hist_kws={'edgecolor': 'black'}, kde_kws={'linewidth':4})

In [ ]:
sns.distplot(c['Travel_History_Yes'], hist=True, kde=True, bins=int (180/5), color= 'darkblue',hist_kws={'edgecolor': 'black'}, kde_kws={'linewidth':4})

In [ ]:
sns.distplot(c['Travel_History_No'], hist=True, kde=True, bins=int (180/5), color= 'darkblue',hist_kws={'edgecolor': 'black'}, kde_kws={'linewidth':4})

In [ ]:
from google.colab import drive
drive.mount('/content/drive')